(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ cd[K[Kpython main-daniel.py
2022-06-22 15:49:14.149901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:49:14.149959: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65421
 * Running on http://172.17.0.2:65421 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 15:49:19.614947: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:49:19.615438: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 15:49:24] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:49:24] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:49:24] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:49:24] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:49:24] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:49:24] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:49:38] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:49:38] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:50:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:05] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:38] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py", line 65, in try_
    prompt=escape(prompt),
NameError: name 'escape' is not defined
127.0.0.1 - - [22/Jun/2022 15:50:38] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:38] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:50:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-22 15:50:58.748010: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:50:58.748057: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python main-daniel.py
2022-06-22 15:51:35.514548: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:51:35.514892: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65421
 * Running on http://172.17.0.2:65421 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 15:51:46.957287: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:51:46.957335: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 15:52:32] "[32mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421 HTTP/1.1[0m" 308 -
127.0.0.1 - - [22/Jun/2022 15:52:32] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:52:32] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:32] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:45] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:52:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:52:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py", line 63
    for 
        ^
SyntaxError: invalid syntax
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python main-daniel.py
2022-06-22 15:56:55.303864: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:56:55.303906: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65421
 * Running on http://172.17.0.2:65421 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 15:57:00.518780: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:57:00.518850: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 15:57:10] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:57:10] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:57:10] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:57:10] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:57:24] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 15:58:00] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:58:00] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:58:00] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 15:58:00] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1" 200 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:58:35.127016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:58:35.127051: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
^C^C(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python main-daniel.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.py[1P.pyd.pyr.pyi.pyz.pyz.pyt.py[1P.pyy.py
2022-06-22 19:22:55.912879: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 19:22:55.912993: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
