(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python rya[Kland.py
2022-06-22 14:46:41.917969: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:46:41.918675: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Serving Flask app 'ryland' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:12345
 * Running on http://172.17.0.2:12345 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 14:46:46.987566: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:46:46.987623: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:46:52] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py", line 49, in my_form
    return render_template('index.html')
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/index.html", line 23, in top-level template code
    <form action="{{ url_for('try_') }}" method="post">
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'try_'. Did you mean 'my_form' instead?
127.0.0.1 - - [22/Jun/2022 14:46:52] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:46:52] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:46:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:46:54] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:47:38.639614: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:47:38.639660: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:49:12.748834: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:49:12.749593: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:49:30.837742: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:49:30.837805: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:50:16.192528: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:50:16.192572: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
pytho     ^C(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ 
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python ryland.py
2022-06-22 14:51:14.728166: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:51:14.728214: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Serving Flask app 'ryland' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:12345
 * Running on http://172.17.0.2:12345 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 14:51:19.903787: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:51:19.903831: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:36] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:44] "[35m[1mPOST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py", line 73, in try_
    prompt = request.form['text']
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'text'
127.0.0.1 - - [22/Jun/2022 14:51:44] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:44] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:45] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:51:45] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:52:12.463474: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:52:12.463530: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:52:31.544612: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:52:31.544663: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:52:38.350296: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:52:38.350341: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:52:48] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:52:48] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:48] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:48] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:48] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:49] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:57] "[35m[1mPOST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py", line 85, in try_
    return render_template('try.html',generated=output)
NameError: name 'output' is not defined
127.0.0.1 - - [22/Jun/2022 14:52:58] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:58] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:52:59] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:53:22.979063: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:53:22.979104: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:53:41.041546: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:53:41.041595: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:53:46] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:53:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:46] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:47] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:51] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:53:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:53:52] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:04] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:54:04] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:04] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:04] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:25] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:54:25] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:25] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:54:25] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:55:58.453878: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:55:58.453922: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:56:21] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 14:56:21] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:56:21] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:56:21] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:56:21] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:56:22] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:57:08.312676: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:57:08.312743: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:57:28.757878: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:57:28.757925: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:57:37.891164: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:57:37.891762: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 14:57:58] "[31m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1[0m" 405 -
127.0.0.1 - - [22/Jun/2022 14:58:05] "[35m[1mPOST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py", line 74, in try_
    amount=request.form['amount']
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/datastructures.py", line 375, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'amount'
127.0.0.1 - - [22/Jun/2022 14:58:05] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:58:05] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:58:06] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 14:58:06] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 14:58:31.413069: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 14:58:31.413113: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:02:50.531082: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:02:50.531128: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/12345/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 15:03:27.787521: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:03:27.787568: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:04:38.347293: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:04:38.347336: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:05:22.666532: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:05:22.666597: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:06:08.179200: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:06:08.179245: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:06:52.690322: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:06:52.690381: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:07:21.016696: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:07:21.016761: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:07:38.299774: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:07:38.299818: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:19:25.268598: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:19:25.268641: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:21:11.750864: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:21:11.752223: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:21:34.797866: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:21:34.797934: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:21:54.307484: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:21:54.308682: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:22:20.375400: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:22:20.376684: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:23:25.807050: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:23:25.807151: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:23:49.757092: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:23:49.758332: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:24:54.697574: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:24:54.698851: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:27:09.962795: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:27:09.964049: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 15:29:51.658715: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:29:51.659470: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy.py', reloading
 * Restarting with stat
2022-06-22 15:30:58.803102: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:30:58.803669: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
^[[A^[[A^[[A            ^[[A
^[[A^[[A        pyrho     P python ryland.py
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:33:14.299616: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:33:14.300554: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:33:59.592914: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:33:59.594081: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:34:43.873373: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:34:43.873414: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:35:30.016813: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:35:30.016874: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:35:49.177904: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:35:49.177953: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:36:13.408450: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:36:13.408496: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:36:34.627700: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:36:34.627742: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:36:57.887320: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:36:57.887377: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:37:19.297910: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:37:19.297959: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:37:43.428490: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:37:43.428533: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:38:29.531475: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:38:29.531536: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:39:08.164766: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:39:08.164824: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:39:57.774935: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:39:57.774974: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:42:45.125848: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:42:45.125918: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:42:58.155147: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:42:58.155192: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:43:19.331897: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:43:19.331943: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:43:43.526594: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:43:43.526891: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:44:04.004977: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:44:04.005037: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy.py', reloading
 * Restarting with stat
2022-06-22 15:44:23.263068: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:44:23.263111: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:44:50.226335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:44:50.227537: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:45:13.696307: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:45:13.697602: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:47:27.726228: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:47:27.727559: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-22 15:48:59.479611: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:48:59.480388: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-22 15:50:58.814058: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:50:58.815366: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-22 15:53:43.371716: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:53:43.371754: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-22 15:54:11.991924: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:54:11.992754: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:56:39.579676: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:56:39.580222: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 15:58:35.126701: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 15:58:35.128001: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main.py', reloading
 * Restarting with stat
2022-06-22 17:04:07.028863: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:04:07.028930: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy.py', reloading
 * Restarting with stat
2022-06-22 17:05:35.164889: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:05:35.165189: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy.py', reloading
 * Restarting with stat
2022-06-22 17:06:05.951684: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:06:05.951752: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 17:07:15.168989: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:07:15.169309: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-22 17:16:26.551193: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:16:26.551267: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main.py', reloading
 * Restarting with stat
2022-06-22 17:22:32.607719: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:22:32.608024: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ 
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python ryland.py
2022-06-22 17:29:27.708005: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:29:27.708049: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Serving Flask app 'ryland' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65421
 * Running on http://172.17.0.2:65421 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-22 17:29:32.998542: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:29:32.998602: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:29:39] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1" 200 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-22 17:31:03.946172: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:31:03.946235: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [22/Jun/2022 17:31:10] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/ HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:31:10] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:31:10] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:31:11] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:31:11] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/index.js HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 17:31:11] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1" 200 -
python drizzy-1.py
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 17:37:32.519702: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:37:32.519749: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 17:37:45.567631: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:37:45.568235: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 17:38:17.096182: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 17:38:17.096832: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
^[[A    python drizzy-1.py
127.0.0.1 - - [22/Jun/2022 18:19:14] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2022 18:19:14] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 18:19:14] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 18:19:14] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [22/Jun/2022 18:19:41] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/try HTTP/1.1" 200 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/drizzy-1.py', reloading
 * Restarting with stat
2022-06-22 18:40:37.860111: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 18:40:37.860466: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/mei.py', reloading
 * Restarting with stat
2022-06-22 18:47:33.256862: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 18:47:33.257049: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allison.py', reloading
 * Restarting with stat
2022-06-22 18:48:32.072681: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-22 18:48:32.073051: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ 